apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-app-green-test
  namespace: weather-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: weather-app-green-test
            port:
              number: 80
        path: /green(/|$)(.*)
        pathType: Prefix