apiVersion: v1
kind: Service
metadata:
  name: weather-app-blue-green
  namespace: weather-app
spec:
  selector:
    app: weather-app
    version: blue  # Początkowo kieruje ruch do wersji blue
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP