apiVersion: v1
kind: Service
metadata:
  name: weather-app-green-test
  namespace: weather-app
spec:
  selector:
    app: weather-app
    version: green 
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP